In [4]:
import numpy as np
np.random.random(size=10)

array([0.80501913, 0.04973857, 0.51955621, 0.29994723, 0.76830522,
       0.44472254, 0.7799125 , 0.01930827, 0.82607451, 0.08891358])

In [4]:
np.random.rand(3,4)

array([[0.43026449, 0.20170841, 0.49238546, 0.61105094],
       [0.27835307, 0.36247776, 0.57828212, 0.80291004],
       [0.66533216, 0.31949404, 0.63688095, 0.73722185]])

In [5]:
np.random.randn(4,4)

array([[-0.80604911,  0.63193356, -1.18747634, -2.91674061],
       [-0.80794455,  1.03841724,  0.21476746, -0.73210067],
       [ 0.09915325, -0.53675893,  0.12701152,  0.38010798],
       [-0.85282174,  0.83388061,  0.97899534,  0.24450326]])

In [17]:
arr=np.random.randint(1000,10000,1)
print(arr)

[1842]


In [19]:
np.arange(10,100,4)

array([10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66, 70, 74,
       78, 82, 86, 90, 94, 98])

In [6]:
myarr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
type(myarr)

numpy.ndarray

In [8]:
myarr.ndim

2

In [9]:
for k in myarr:
    for i in k:
        print(i)

1
2
3
4
5
6
7
8
9
10
11
12
